movimento/urls.py
from django.urls import path

from . import views

app_name = 'movimento'

urlpatterns = [
    path('', views.index, name='index'),
    path('transacoes/', views.transacoes, name='transacoes'),
    path('transacoes/novo', views.transacoesNovo, name='transacoesNovo'),
    path('transacoes/ver/<int:transacao_id>/', views.transacoesVer, name='transacoesVer'),
    path('transacoes/editar/<int:transacao_id>/', views.transacoesEditar, name='transacoesEditar'),
    path('transacoes/confirmar_apagar/<int:transacao_id>/', views.transacoesConfirmarApagar, name='transacoesConfirmarApagar'),
    path('transacoes/apagar/<int:transacao_id>/', views.transacoesApagar, name='transacoesApagar'),
    
    path('compras/', views.transacoesCompra, name='transacoesCompra'),

    path('vendas/', views.transacoesVenda, name='transacoesVenda'),
    path('vendaCliente/<int:cliente_id>/', views.transacoesVendaCliente, name='transacoesVendaCliente'),
]

registros/urls.py
from django.urls import path

from . import views

app_name = 'registros'

urlpatterns = [
    path('', views.index, name='index'),
    path('produtos/', views.produtos, name='produtos'),
    path('produtos/novo/', views.produtosNovo, name='produtosNovo'),
    path('produtos/ver/<int:produto_id>/', views.produtosVer, name='produtosVer'),
    path('produtos/editar/<int:produto_id>/', views.produtosEditar, name='produtosEditar'),
    path('produtos/confirmar_apagar/<int:produto_id>/', views.produtosConfirmarApagar, name='produtosConfirmarApagar'),
    path('produtos/apagar/<int:produto_id>', views.produtosApagar, name='produtosApagar'),
    
    path('clientes/', views.clientes, name='clientes'),
    path('clientes/novo/', views.clientesNovo, name='clientesNovo'),
    path('clientes/ver/<int:cliente_id>/', views.clientesVer, name='clientesVer'),
    path('clientes/editar/<int:cliente_id>/', views.clientesEditar, name='clientesEditar'),
    path('clientes/confirmar_apagar/<int:cliente_id>/', views.clientesConfirmarApagar, name='clientesConfirmarApagar'),
    path('clientes/apagar/<int:cliente_id>/', views.clientesApagar, name='clientesApagar'),
]

sistema/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('catalogo.urls')),
    path('admin/', admin.site.urls, name='admin'),
    path('sistema/', include('sitewide.urls')),
    path('registros/', include('registros.urls')),
    path('movimento/', include('movimento.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

movimento/models.py
from datetime import date

from django.db import models

from django.db.models import Model
from django.db.models import CharField, IntegerField, DateField
from django.db.models import ForeignKey, CASCADE, SET_NULL
from django.contrib.auth.models import User

class Transacao(Model):
    vendedor = ForeignKey('registros.Empresa', related_name="empresa_vendedora", on_delete=SET_NULL, null=True)
    comprador = ForeignKey('registros.Empresa', related_name="empresa_compradora", on_delete=SET_NULL, null=True)
    data = DateField(default=date.today)
    moeda = ForeignKey('registros.Moeda', on_delete=SET_NULL, null=True)

    class Meta:
        verbose_name_plural = "Transações"
        ordering = ['-data']

    def total(self):
        out = 0
        for item in self.itens.all():
            out += item.total()
        return out
        
    def __str__(self):
        fmt = "[{}] {} {} --> {} ({} {})"
        return fmt.format(self.id, self.data,
                          self.vendedor, self.comprador,
                          self.moeda, self.total())

class ItemDeLinha(Model):
    transacao = ForeignKey(Transacao, related_name='itens', on_delete=CASCADE)
    qtde = IntegerField(blank=True, null=True)
    produto = ForeignKey('registros.Produto', on_delete=SET_NULL, null=True)
    preco_unitario = IntegerField(blank=True, null=True)

    class Meta:
        verbose_name_plural = "Itens de Linha"

    def total(self):
        try:
            return self.qtde * self.preco_unitario
        except TypeError:
            return 0
    
    def __str__(self):
        fmt = "[{}] {} --> {}: {} pc {} @ {} {} = {}"
        return fmt.format(self.transacao.data,
                          self.transacao.vendedor, self.transacao.comprador,
                          self.qtde, self.produto,
                          self.transacao.moeda, self.preco_unitario,
                          self.total())

movimento/forms.py
import datetime
from django import forms

from django.forms import ModelForm, TextInput, inlineformset_factory, ChoiceField

from registros.models import Empresa
from .models import Transacao, ItemDeLinha

class TransacaoForm(ModelForm):
    class Meta:
        model = Transacao
        fields = '__all__'

ItemDeLinhaFormSet = inlineformset_factory(Transacao, ItemDeLinha, exclude=("transacao", ), extra=5)

movimento/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse

from registros.models import Empresa, Configuracao

from .models import Transacao, ItemDeLinha
from .forms import TransacaoForm, ItemDeLinhaFormSet

def index(request):
    return render(request, 'movimento/index.html')


def transacoes(request):
    transacoes = Transacao.objects.all().order_by('-data', '-id')
    
    context = {'transacoes': transacoes}
    return render(request, 'movimento/transacoes/todos.html', context)


def transacoesNovo(request, tipo="padrao", comprador=None):
    context = {}
    configuracao = Configuracao.objects.get()
    moeda_principal = configuracao.moeda_principal.id
    
    if request.method == "POST":
        form = TransacaoForm(request.POST)
        if form.is_valid():
            transacao_nova = form.save()
            formset = ItemDeLinhaFormSet(request.POST, instance=transacao_nova)
        
            if formset.is_valid():
                formset.save()
                transacao_id = transacao_nova.id
                return HttpResponseRedirect(reverse('movimento:transacoesVer', kwargs={'transacao_id': transacao_id}))
            else:
                erro_descricao = formset
                return render(request, 'sitewide/erro.html',
                              {'erro_descricao': erro_descricao})
        else:
            erro_descricao = form
            return render(request, 'sitewide/erro.html',
                          {'erro_descricao': erro_descricao})
    else:
        empresa_ativa_id = configuracao.empresa_ativa.id
        if tipo == "venda":
            context['form'] = TransacaoForm(initial={'vendedor': empresa_ativa_id, 'moeda': moeda_principal})
            context['label'] = "Venda"
            if comprador is not None:
                context['form'] = TransacaoForm(initial={'vendedor': empresa_ativa_id, 'comprador': comprador, 'moeda': moeda_principal})
        elif tipo == "compra":
            context['form'] = TransacaoForm(initial={'comprador': empresa_ativa_id, 'moeda': moeda_principal})
            context['label'] = "Compra"
        else:
            # padrao
            context['form'] = TransacaoForm(initial={'moeda': moeda_principal})
            context['label'] = "Transação"
                        
        context['formset'] = ItemDeLinhaFormSet()
    return render(request, 'movimento/transacoes/novo.html', context)
    
def transacoesCompra(request):
    return transacoesNovo(request, "compra")


def transacoesVenda(request):
    return transacoesNovo(request, "venda")

def transacoesVendaCliente(request, cliente_id):
    return transacoesNovo(request, "venda", cliente_id)

def transacoesVer(request, transacao_id):
    transacao = get_object_or_404(Transacao, pk=transacao_id)
    itensDeLinha = transacao.itens.all()
    
    context = {'transacao': transacao, 'itensDeLinha': itensDeLinha}
    return render(request, 'movimento/transacoes/ver.html', context)


def transacoesEditar(request, transacao_id):
    context = {}
    transacao = get_object_or_404(Transacao, pk=transacao_id)
    context['transacao'] = transacao
    
    if request.method == "POST":
        form = TransacaoForm(request.POST, instance=transacao)
        formset = ItemDeLinhaFormSet(request.POST, instance=transacao)
        if form.is_valid() and formset.is_valid():
            form.save()
            formset.save()
            return HttpResponseRedirect(reverse('movimento:transacoesVer', kwargs={'transacao_id': transacao_id}))
        else:
            erro_descricao = formset
            return render(request, 'sitewide/erro.html',
                          {'erro_descricao': erro_descricao})
    else:
        context['form'] = TransacaoForm(instance=transacao)
        context['formset'] = ItemDeLinhaFormSet(instance=transacao)
    return render(request, 'movimento/transacoes/editar.html', context)


def transacoesConfirmarApagar(request, transacao_id):
    transacao = get_object_or_404(Transacao, pk=transacao_id)

    context = {'transacao': transacao}
    return render(request, 'movimento/transacoes/confirmarApagar.html', context)


def transacoesApagar(request, transacao_id):
    transacao = get_object_or_404(Transacao, pk=transacao_id)
    transacao.delete()
    
    return HttpResponseRedirect(reverse('movimento:transacoes'))

movimento/templates/movimento/transacoes/confirmarApagar.html
{% extends 'sitewide/bootstrap/base.html' %}

{% block title %}Transações - Movimento{% endblock %}
{% block headerTitle %}Movimento - Transações{% endblock %}

{% block mainTitle %}Realmente apagar {{ transacao }}?{% endblock %}

{% block actionTop %}
<a href="{% url "movimento:transacoes" %}" class="btn btn-primary">Todas as Transações</a>

{% endblock %}


{% block main %}

<h3>

<a href="{% url "movimento:transacoesApagar" transacao_id=transacao.id %}" class="btn btn-danger">Sim, apagar</a>

<br><br><br>

<a href="{% url "movimento:transacoesVer" transacao_id=transacao.id %}" class="btn btn-primary">Não, voltar</a>

{% endblock %}

movimento/templates/movimento/transacoes/editar.html
{% extends 'sitewide/bootstrap/base.html' %}

{% block title %}Transações - Registros{% endblock %}
{% block headerTitle %}Registros - Transações{% endblock %}

{% block mainTitle %}Editar Transação{% endblock %}

{% block actionTop %}
<a href="{% url "movimento:transacoes" %}" class="btn btn-primary">Voltar</a>
{% endblock %}

{% block main %}

<h3>{{ transacao }}</h3>

<form method="post">
    {% csrf_token %}

    <table>
        {{ form.as_table }}
    </table>

    <br>
    
    {{ formset.management_form }}
    {% for row in formset %}
    <ul class="ul-columns">
        {{ row.as_ul }}
    </ul>
    <div class="clear-both"></div>
    {% endfor %}

    <input type="submit" class="btn btn-success" value="Salvar">
</form>

{% endblock %}

movimento/templates/movimento/transacoes/novo.html
{% extends 'sitewide/bootstrap/base.html' %}

{% block title %}Transações - Registros{% endblock %}
{% block headerTitle %}Registros - Transações{% endblock %}

{% block mainTitle %}{{ label }} Nova{% endblock %}

{% block actionTop %}
<a href="{% url "movimento:transacoes" %}" class="btn btn-primary">Voltar</a>
{% endblock %}

{% block main %}

<form method="post">
    {% csrf_token %}

    <table>
        {{ form.as_table }}
    </table>

    <br>

    {{ formset.management_form }}
    {% for row in formset %}
        <ul class="ul-columns">
        {{ row.as_ul }}
    </ul>
    <div class="clear-both"></div>
    {% endfor %}

    <input type="submit" class="btn btn-success" value="Concluir">
</form>

{% endblock %}

movimento/templates/movimento/transacoes/todos.html
{% extends 'sitewide/bootstrap/base.html' %}

{% block title %}Transações - Movimento{% endblock %}
{% block headerTitle %}Movimento - Transações{% endblock %}

{% block mainTitle %}Transações{% endblock %}

{% block actionTop %}
<a href="{% url "movimento:transacoesNovo" %}" class="btn btn-primary">Transação Nova</a>
{% endblock %}


{% block main %}

{% include "movimento/transacoes/tabelas/transacoes.html" %}

{% endblock %}

movimento/templates/movimento/transacoes/ver.html
{% extends 'sitewide/bootstrap/base.html' %}

{% block title %}Transações - Movimento{% endblock %}
{% block headerTitle %}Movimento - Transações{% endblock %}

{% block mainTitle %}
[{{ transacao.id }}] {{ transacao.data }}
<a href="{% url "registros:clientesVer" transacao.comprador.id %}">
    {{ transacao.comprador }}
</a>
{% endblock %}

{% block actionTop %}
<a href="{% url "movimento:transacoesNovo" %}" class="btn btn-primary">Transação Nova</a>
<a href="{% url "movimento:transacoes" %}" class="btn btn-primary">Todas as Transações</a>

{% endblock %}


{% block main %}
<br>

<a href="{% url "movimento:transacoesEditar" transacao_id=transacao.id %}" class="btn btn-secondary">Editar</a>

<a href="{% url "movimento:transacoesConfirmarApagar" transacao_id=transacao.id %}" class="btn btn-danger">Apagar</a>

<br><br>

<p>
    Total: {{ transacao.moeda }} {{ transacao.total }}
</p>
   
{% include "movimento/transacoes/tabelas/itensDeLinhaTotal.html" %}

{% endblock %}