registros/urls.py
from django.urls import path

from . import views

app_name = 'registros'

urlpatterns = [
    path('', views.index, name='index'),
    path('produtos/', views.produtos, name='produtos'),
    path('produtos/novo/', views.produtosNovo, name='produtosNovo'),
    path('produtos/ver/<int:produto_id>/', views.produtosVer, name='produtosVer'),
    path('produtos/editar/<int:produto_id>/', views.produtosEditar, name='produtosEditar'),
    path('produtos/confirmar_apagar/<int:produto_id>/', views.produtosConfirmarApagar, name='produtosConfirmarApagar'),
    path('produtos/apagar/<int:produto_id>', views.produtosApagar, name='produtosApagar'),
    
    path('clientes/', views.clientes, name='clientes'),
    path('clientes/novo/', views.clientesNovo, name='clientesNovo'),
    path('clientes/ver/<int:cliente_id>/', views.clientesVer, name='clientesVer'),
    path('clientes/editar/<int:cliente_id>/', views.clientesEditar, name='clientesEditar'),
    path('clientes/confirmar_apagar/<int:cliente_id>/', views.clientesConfirmarApagar, name='clientesConfirmarApagar'),
    path('clientes/apagar/<int:cliente_id>/', views.clientesApagar, name='clientesApagar'),
]

sistema/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('catalogo.urls')),
    path('admin/', admin.site.urls, name='admin'),
    path('sistema/', include('sitewide.urls')),
    path('registros/', include('registros.urls')),
    path('movimento/', include('movimento.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

registros/models.py
from datetime import date
from collections import defaultdict

from django.db import models

from django.db.models import Model
from django.db.models import ImageField, EmailField, DateField
from django.db.models import CharField, IntegerField, BooleanField
from django.db.models import ForeignKey, CASCADE, SET_NULL
from django.contrib.auth.models import User

from movimento.models import ItemDeLinha

class Moeda(Model):
    nome = CharField(max_length=63)
    codigo = CharField(max_length=6, verbose_name="Código")
    mostrar_centavos = BooleanField(default=True)

    class Meta:
        ordering = ['codigo']
        
    def __str__(self):
        return self.codigo

    
class Empresa(Model):
    nome = CharField(max_length=255)

    # Endereço
    rua = CharField(max_length=255, blank=True)
    bairro = CharField(max_length=63, blank=True)
    cidade = CharField(max_length=63, blank=True)
    estado = CharField(max_length=63, blank=True)
    cep = CharField(max_length=15, blank=True, verbose_name="CEP")
    pais = CharField(max_length=31, blank=True, verbose_name="País")

    # Contato
    contato = CharField(max_length=63, blank=True) 
    telefone = CharField(max_length=31, blank=True)
    email = EmailField(blank=True)

    # Cadastros 
    cadastro_nacional = CharField(max_length=35, blank=True, verbose_name="CNPJ")
    cadastro_estadual = CharField(max_length=35, blank=True, verbose_name="Inscrição Estadual")
    cadastro_municipal = CharField(max_length=35, blank=True, verbose_name="Inscrição Municipal")

    # funcionario responsavel pelo cliente
    vendedor = ForeignKey('Funcionario', blank=True, null=True, on_delete=SET_NULL)
    
    class Meta:
        ordering = ['nome'] 

    def vendas(self):
        transacoes = self.empresa_compradora.all().order_by('-data', '-id')
        return transacoes

    def totais(self):
        transacoes = self.empresa_compradora.all().order_by('-data', '-id')
        totais_dict = defaultdict(int)

        for transacao in transacoes:
            totais_dict[transacao.moeda.codigo] += transacao.total()

        out = []
        
        for codigo in sorted(dict(totais_dict)):
            out.append({'codigo': codigo, 'valor': totais_dict[codigo]})

        return out
            
    def __str__(self):
        return "{} [{}]".format(self.nome, self.id)

class Funcionario(Model):
    user = models.OneToOneField(User, on_delete=CASCADE)
    empregador = ForeignKey(Empresa, on_delete=SET_NULL, null=True)

    class Meta:
        verbose_name_plural = "Funcionários" 
        ordering = ['user__username'] 
    
    def __str__(self):
        return self.user.username

class Configuracao(Model):
    empresa_ativa = ForeignKey(Empresa, blank=True, null=True, on_delete=SET_NULL)
    moeda_principal = ForeignKey(Moeda, blank=True, null=True, on_delete=SET_NULL)

    class Meta:
        verbose_name_plural = "Configurações"
        
    def __str__(self):
        return "Empresa ativa: " + self.empresa_ativa.nome


class Produto(Model):
    codigo = CharField(max_length=63, verbose_name="Código")
    nome = CharField(max_length=127)
    por_caixa = IntegerField(default=1)
    foto = ImageField(upload_to='products/', blank=True, null=True)

    class Meta:
        ordering = ['codigo'] 

    def estoque(self):
        compras = self.compras()
        vendas = self.vendas()
        estoque = 0

        for compra in compras:
            estoque += compra.qtde

        for venda in vendas:
            estoque -= venda.qtde

        return estoque

    def compras(self):
        empresa_ativa = Configuracao.objects.get().empresa_ativa
        return ItemDeLinha.objects.filter(transacao__comprador=empresa_ativa, produto=self).order_by('-id')

    def vendas(self):
        empresa_ativa = Configuracao.objects.get().empresa_ativa
        return ItemDeLinha.objects.filter(transacao__vendedor=empresa_ativa, produto=self).order_by('-id')
        
    
    def __str__(self):
        return self.codigo

registros/forms.py
from django.forms import ModelForm, TextInput

from .models import Empresa, Produto

class ClienteForm(ModelForm):
    class Meta:
        model = Empresa
        fields = '__all__'
        widgets = {'nome': TextInput(attrs={'autofocus': 'autofocus'})}


        
class ProdutoForm(ModelForm):
    class Meta:
        model = Produto
        fields = '__all__'
        widgets = {'codigo': TextInput(attrs={'autofocus': 'autofocus'})}
        

registros/views.py
from django.shortcuts import render, get_object_or_404
from django.db.models.functions import Lower
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

from movimento.models import ItemDeLinha

from .models import Empresa, Produto, Configuracao
from .forms import ClienteForm, ProdutoForm

def index(request):
    return render(request, 'registros/index.html')


# PAGINATOR SUB-RANGE

def subRange(lastPage, currentPage, width):
    currentPage = int(currentPage)
    return range(max(1, currentPage-width), min(lastPage, currentPage+width)+1)
    
    
# PRODUTOS

def produtos(request):
    produtos = Produto.objects.all().order_by('codigo')

    PRODUTOS_POR_PAGINA = 8
    LINKS_NO_PAGINATOR = 5
    
    paginator = Paginator(produtos, PRODUTOS_POR_PAGINA)
    page = request.GET.get('page', 1)

    try:
        produtos_page = paginator.page(page)
    except PageNotAnInteger:
        produtos_page = paginator.page(1)
    except EmptyPage:
        produtos_page = paginator.page(paginator.num_pages)
        
    context = {'produtos': produtos_page,
               'last_page': paginator.num_pages,
               'show_page_range': subRange(paginator.num_pages, page, LINKS_NO_PAGINATOR)}
    return render(request, 'registros/produtos/todos.html', context)


def produtosNovo(request):
    context = {}

    if request.method == "POST":
        form = ProdutoForm(request.POST, request.FILES)
        if form.is_valid():
            produto_novo = form.save()
            produto_id = produto_novo.id 
            return HttpResponseRedirect(reverse('registros:produtosVer', kwargs={'produto_id': produto_id}))
        else:
            erro_descricao = form
            return render(request, 'sitewide/erro.html',
                          {'erro_descricao': erro_descricao})
    else:
        form = ProdutoForm()
        context['form'] = form
    
    return render(request, 'registros/produtos/novo.html', context)
    

def produtosVer(request, produto_id):
    produto = get_object_or_404(Produto, pk=produto_id)

    context = {'produto': produto}
    return render(request, 'registros/produtos/ver.html', context)


def produtosEditar(request, produto_id):
    produto = get_object_or_404(Produto, pk=produto_id)

    if request.method == "POST":
        form = ProdutoForm(request.POST, request.FILES, instance=produto)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('registros:produtosVer', kwargs={'produto_id': produto_id}))
        else:
            erro_descricao = form
            return render(request, 'sitewide/erro.html',
                          {'erro_descricao': erro_descricao})
    else:
        form = ProdutoForm(instance=produto)
        return render(request, 'registros/produtos/editar.html', {'form': form})


def produtosConfirmarApagar(request, produto_id):
    produto = get_object_or_404(Produto, pk=produto_id)
    context = {'produto': produto}
    
    return render(request, 'registros/produtos/confirmarApagar.html', context)


def produtosApagar(request, produto_id):
    produto = get_object_or_404(Produto, pk=produto_id)
    produto.delete()
    
    return HttpResponseRedirect(reverse('registros:produtos'))


# CLIENTES

def clientes(request):
    clientes = Empresa.objects.all().order_by(Lower('nome'))

    CLIENTES_POR_PAGINA = 12
    LINKS_NO_PAGINATOR = 5
    
    paginator = Paginator(clientes, CLIENTES_POR_PAGINA)
    page = request.GET.get('page', 1)

    try:
        clientes_page = paginator.page(page)
    except PageNotAnInteger:
        clientes_page = paginator.page(1)
    except EmptyPage:
        clientes_page = paginator.page(paginator.num_pages)
        
    context = {'clientes': clientes_page,
               'last_page': paginator.num_pages,
               'show_page_range': subRange(paginator.num_pages, page, LINKS_NO_PAGINATOR)}
    return render(request, 'registros/clientes/todos.html', context)


def clientesNovo(request):
    context = {}
    
    if request.method == "POST":
        form = ClienteForm(request.POST)
        if form.is_valid():
            cliente_novo = form.save()
            cliente_id = cliente_novo.id 
            return HttpResponseRedirect(reverse('registros:clientesVer', kwargs={'cliente_id': cliente_id}))
        else:
            erro_descricao = form
            return render(request, 'sitewide/erro.html',
                          {'erro_descricao': erro_descricao})
    else:
        form = ClienteForm()
        context['form'] = form
    return render(request, 'registros/clientes/novo.html', context)


def clientesVer(request, cliente_id):
    cliente = get_object_or_404(Empresa, pk=cliente_id)
    vendas = cliente.vendas()
    totais = cliente.totais()
    gmaps_place = "{} {} {} CEP {}".format(cliente.rua, cliente.cidade, cliente.estado, cliente.cep).replace(" ", "+")
    
    context = {'cliente': cliente, 'vendas': vendas, 'totais': totais, 'gmaps_place': gmaps_place}
    return render(request, 'registros/clientes/ver.html', context)


def clientesEditar(request, cliente_id):
    cliente = get_object_or_404(Empresa, pk=cliente_id)

    form = ClienteForm(request.POST or None, instance=cliente)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('registros:clientesVer', kwargs={'cliente_id': cliente_id}))
    return render(request, 'registros/clientes/editar.html', {'form': form})


def clientesConfirmarApagar(request, cliente_id):
    cliente = get_object_or_404(Empresa, pk=cliente_id)

    context = {'cliente': cliente}
    return render(request, 'registros/clientes/confirmarApagar.html', context)

def clientesApagar(request, cliente_id):
    cliente = get_object_or_404(Empresa, pk=cliente_id)
    cliente.delete()

    return HttpResponseRedirect(reverse('registros:clientes'))

registros/templates/registros/bootstrap/cliente.html
{% extends 'sitewide/bootstrap/base.html' %}

{% block title %}Clientes - Registros{% endblock %}
{% block headerTitle %}Registros - Clientes{% endblock %}

{% block mainTitle %}Cliente - {{ cliente.nome }}{% endblock %}

{% block actionTop %}
<a href="{% url "registros:clientes" %}" class="btn btn-primary">Todos os Clientes</a>
{% endblock %}


{% block main %}



{{ cliente.rua }}
{{ cliente.cidade }}

{% endblock %}

registros/templates/registros/bootstrap/clientes.html
{% extends 'sitewide/bootstrap/base.html' %}

{% block title %}Clientes - Registros{% endblock %}
{% block headerTitle %}Registros - Clientes{% endblock %}

{% block mainTitle %}Clientes{% endblock %}

{% block actionTop %}
<a href="{% url "registros:clientesNovo" %}" class="btn btn-primary">Cliente Novo</a>
{% endblock %}


{% block main %}

{% for cliente in clientes %}
<div class="card">
    <div class="card-body">
        <a href="{% url "registros:clientesVer" cliente_id=cliente.id %}">
            <h5 class="card-title">{{ cliente.nome }} ({{ cliente.id }})</h5>
        </a>
           
        <p class="card-text">
            {{ cliente.rua }}
            {{ cliente.cidade }}
        </p>
    </div>
</div>
{% endfor %}

{% endblock %}

registros/templates/registros/bootstrap/clientesApagar.html
{% extends 'sitewide/bootstrap/base.html' %}

{% block title %}Clientes - Registros{% endblock %}
{% block headerTitle %}Registros - Clientes{% endblock %}

{% block mainTitle %}Realmente apagar {{ cliente.nome }}?{% endblock %}

{% block actionTop %}
<a href="{% url "registros:clientes" %}" class="btn btn-primary">Todos os Clientes</a>

{% endblock %}


{% block main %}

<h3>

<a href="{% url "registros:clientesEditar" cliente_id=cliente.id %}" class="btn btn-danger">Sim, apagar</a>

<br><br><br>

<a href="{% url "registros:clientesVer" cliente_id=cliente.id %}" class="btn btn-primary">Não, voltar</a>

{% endblock %}

registros/templates/registros/bootstrap/clientesConfirmarApagar.html
{% extends 'sitewide/bootstrap/base.html' %}

{% block title %}Clientes - Registros{% endblock %}
{% block headerTitle %}Registros - Clientes{% endblock %}

{% block mainTitle %}Realmente apagar {{ cliente.nome }}?{% endblock %}

{% block actionTop %}
<a href="{% url "registros:clientes" %}" class="btn btn-primary">Todos os Clientes</a>

{% endblock %}


{% block main %}

<h3>

<a href="{% url "registros:clientesApagar" cliente_id=cliente.id %}" class="btn btn-danger">Sim, apagar</a>

<br><br><br>

<a href="{% url "registros:clientesVer" cliente_id=cliente.id %}" class="btn btn-primary">Não, voltar</a>

{% endblock %}

registros/templates/registros/bootstrap/clientesEditar.html
{% extends 'sitewide/bootstrap/base.html' %}

{% block title %}Clientes - Registros{% endblock %}
{% block headerTitle %}Registros - Clientes{% endblock %}

{% block mainTitle %}Editar Cliente{% endblock %}

{% block actionTop %}
<a href="{% url "registros:clientes" %}" class="btn btn-primary">Voltar</a>
{% endblock %}

{% block main %}

<form method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>

    <input type="submit">
</form>

{% endblock %}

registros/templates/registros/bootstrap/clientesNovo.html
{% extends 'sitewide/bootstrap/base.html' %}

{% block title %}Clientes - Registros{% endblock %}
{% block headerTitle %}Registros - Clientes{% endblock %}

{% block mainTitle %}Cliente Novo{% endblock %}

{% block actionTop %}
<a href="{% url "registros:clientes" %}" class="btn btn-primary">Voltar</a>
{% endblock %}

{% block main %}

<form method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>

    <input type="submit" class="btn btn-success" value="Concluir">
</form>

{% endblock %}

registros/templates/registros/bootstrap/clientesVer.html
{% extends 'sitewide/bootstrap/base.html' %}

{% block title %}Clientes - Registros{% endblock %}
{% block headerTitle %}Registros - Clientes{% endblock %}

{% block mainTitle %}Cliente - {{ cliente.nome }}{% endblock %}

{% block actionTop %}
<a href="{% url "registros:clientes" %}" class="btn btn-primary">Todos os Clientes</a>

{% endblock %}


{% block main %}

<a href="{% url "registros:clientesEditar" cliente_id=cliente.id %}" class="btn btn-secondary">Editar</a>

<a href="{% url "registros:clientesConfirmarApagar" cliente_id=cliente.id %}" class="btn btn-danger">Apagar</a>

<p>
    <b>Endereço:</b>
    {{ cliente.rua }},
    {{ cliente.cidade }},
    {{ cliente.estado }},
    {{ cliente.pais }},
    CEP {{ cliente.cep }}
</p>

<p>
    <b>Contato:</b>
    {{ cliente.contato }}<br>
    {{ cliente.telefone }}<br>
    {{ cliente.email }}
</p>

<p>
    <b>Cadastros:</b>
    <br>
    CNPJ {{ cliente.cadastro_nacional }}<br>
    I.E. {{ cliente.cadastro_estadual }}<br>
    I.M. {{ cliente.cadastro_municipal }}
</p>

{% endblock %}

registros/templates/registros/bootstrap/produtos.html
{% extends 'sitewide/bootstrap/base.html' %}
{% load static %}

{% block title %}Produtos - Registros{% endblock %}
{% block headerTitle %}Registros - Produtos{% endblock %}

{% block mainTitle %}Produtos{% endblock %}

{% block actionTop %}
<a href="{% url "registros:produtosNovo" %}" class="btn btn-primary">Produto Novo</a>
{% endblock %}


{% block main %}

{% for produto in produtos %}
<div class="card card-small">
    <a href="{% url "registros:produtosVer" produto_id=produto.id %}">
        <img class="card-img-top" src="{% if produto.foto %}{{ produto.foto.url }}{% else %}{% static "img/question_mark.png" %}{% endif %}" alt="{{ produto.codigo }}">
    </a>
    
    <div class="card-body">
        <a href="{% url "registros:produtosVer" produto_id=produto.id %}">
            <h5 class="card-title">{{ produto.nome }} ({{ produto.id }})</h5>
        </a>
           
        <p class="card-text">
            
            {{ produto.codigo }}
            {{ produto.nome }}
        </p>
    </div>
</div>
{% endfor %}

{% endblock %}

registros/templates/registros/bootstrap/produtosVer.html
{% extends 'sitewide/bootstrap/base.html' %}
{% load static %}

{% block title %}Produtos - Registros{% endblock %}
{% block headerTitle %}Registros - Produtos{% endblock %}

{% block mainTitle %}Produto - {{ produto.nome }}{% endblock %}

{% block actionTop %}
<a href="{% url "registros:produtos" %}" class="btn btn-primary">Todos os Produtos</a>

{% endblock %}


{% block main %}

<a href="{% url "registros:produtosEditar" produto_id=produto.id %}" class="btn btn-secondary">Editar</a>

<a href="{% url "registros:produtosConfirmarApagar" produto_id=produto.id %}" class="btn btn-danger">Apagar</a>

<br><br>
    
<p>
    <span class="font-weight-bold">{{ produto.codigo }}</span>
    {{ produto.nome }}
    ({{ produto.por_caixa }} peças por caixa)
</p>

<p>
    <a href="{% if produto.foto %}{{ produto.foto.url }}{% else %}#{% endif %}">
        <img src="{% if produto.foto %}{{ produto.foto.url }}{% else %}{% static "img/question_mark.png" %}{% endif %}" alt="{{ produto.codigo }}" class="foto-small">
    </a>
</p>

{% endblock %}