catalogo/urls.py
from django.urls import path

from . import views

app_name = 'catalogo'

urlpatterns = [
    path('', views.index, name='index'),
    path('catalogo/lista/<int:lista_id>/', views.lista, name='lista'),
    path('busca', views.busca, name='busca'),
]

sistema/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('catalogo.urls')),
    path('admin/', admin.site.urls, name='admin'),
    path('sistema/', include('sitewide.urls')),
    path('registros/', include('registros.urls')),
    path('movimento/', include('movimento.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sitewide/urls.py
from django.urls import path

from . import views

app_name = 'sitewide'

urlpatterns = [
    path('', views.index, name='index'),
    path('search', views.search, name='search'),
    path('mdc/', views.indexMDC, name='indexMDC'),
]

catalogo/models.py
from django.db import models
from django.db.models import Model
from django.db.models import CharField
from django.db.models import ForeignKey, CASCADE, SET_NULL

from registros.models import Produto


class MenuPasta(Model):
    nome = CharField(max_length=79)

    class Meta:
        ordering = ['nome']
        
    def __str__(self):
        return self.nome
        

class Lista(Model):
    nome = CharField(max_length=79)

    class Meta:
        ordering = ['nome']
        
    def __str__(self):
        return self.nome


class MenuItem(Model):
    nome = CharField(max_length=79)
    lista = ForeignKey(Lista, on_delete=CASCADE)
    pasta = ForeignKey(MenuPasta, on_delete=CASCADE)

    class Meta:
        verbose_name_plural = "Menu itens"
        ordering = ['nome']        
        
    def __str__(self):
        return self.nome
        

class Item(Model):
    produto = models.OneToOneField(Produto, on_delete=CASCADE)
    listas = models.ManyToManyField(Lista, blank=True)
    
    class Meta:
        verbose_name_plural = "Itens"
        ordering = ["produto__codigo"]
        
    def __str__(self):
        return "[{}] {}".format(self.produto.codigo, self.produto.nome)

catalogo/views.py
from django.shortcuts import render

from .models import MenuPasta, Lista, Item

def index(request):
    pastas = MenuPasta.objects.all().order_by('nome')
    
    return render(request, 'catalogo/index.html', {'pastas': pastas})


def lista(request, lista_id):
    pastas = MenuPasta.objects.all().order_by('nome')
    lista = Lista.objects.get(pk=lista_id)
    itens = lista.item_set.all()
    
    return render(request, 'catalogo/lista.html',
                  {'pastas': pastas, 'lista_nome': lista.nome, 'itens': itens})


def busca(request):
    pastas = MenuPasta.objects.all().order_by('nome')

    query = request.GET['q']

    if query:
        itens = Item.objects.filter(produto__codigo__icontains=query) | Item.objects.filter(produto__nome__icontains=query)
    else:
        itens = Item.objects.none()

    return render(request, 'catalogo/busca_resultado.html',
                  {'query': query, 'itens': itens, 'pastas': pastas})

catalogo/templates/catalogo/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="shortcut icon" href="{% static "img/favicon-ptl.ico" %}">
        
        <title>Pontual Import Brindes - Pontual Exportação e Importação Ltda. - Homepage</title>
        <link rel="stylesheet" href="{% static "css/catalogo/myFonts.css" %}">
        <link rel="stylesheet" href="{% static "css/catalogo/jquery.mobile-1.4.5.min.css" %}">
        <link rel="stylesheet" href="{% static "css/catalogo/themes/jquery.mobile.icons.min.css" %}">
        <link rel="stylesheet" href="{% static "css/catalogo/themes/ptl2016.min.css" %}">
        <link rel="stylesheet" href="{% static "css/catalogo/drift-basic.min.css" %}">
        <link rel="stylesheet" href="{% static "css/catalogo/materialCard.css" %}">
        <link rel="stylesheet" href="{% static "css/catalogo/menuStyle.css" %}">
        <link rel="stylesheet" href="{% static "css/catalogo/myStyle.css" %}">
    </head>
    <body>
        <script src="{% static "js/catalogo/jquery-1.12.4.min.js" %}"></script>
        <script src="{% static "js/catalogo/jquery.mobile-1.4.5.min.js" %}"></script>
        <script src="{% static "js/catalogo/jquery.mobile-panel-hack.js" %}"></script>
        <script src="{% static "js/catalogo/drift.min.js" %}"></script>

        {% include "catalogo/menu.html" %}


        <!-- Dynamic page title in data-title -->
        <div data-role="page" data-theme="a" data-title="Pontual Import Brindes - Pontual Exportação e Importação Ltda. - Homepage" data-ajax="false" id="produtos-page">

            <!-- HEADER -->
            <div data-role="header" data-position="fixed" data-tap-toggle="false" style="overflow: hidden;">
                
                <div data-role="navbar">
                    <ul>
                        <li>
                            <a href="#menu" data-rel="panel" class="ui-btn-left ui-btn ui-btn-icon-left ui-icon-bars" onclick="$('body,html').animate({scrollTop:0},150);">Menu</a>
                        </li>

                        <li>
                            <!-- SEARCH -->
                            <form action="{% url "catalogo:busca" %}" method="GET" data-ajax="false">
                                <input name="q" id="search" value="" placeholder="Busca" type="search" data-mini="true">
                            </form>
                        </li>
                    </ul>
                </div>
            </div> <!-- END Header -->

            <div class="center-div" data-role="content">

                <!-- Endereço, Telefones -->
                
                <table class="info_table">
                    <tr>
                        <td>
                            <a href="{% url "catalogo:index" %}" data-ajax="false">
                                <img src="{% static "css/catalogo/img/logo.jpg" %}" alt="Logo">
                            </a>
                        </td>
                        <td class="info_header table_left table_vertical_bottom">
                            <!-- Pontual Import Brindes -->
                            <a href="{% url "catalogo:index" %}" data-ajax="false">
                                Pontual Import Brindes            </a>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <a href="#" data-ajax="false">
                                <img src="{% static "css/catalogo/img/icomoon-location.png" %}" alt="Endereço" title="Localização">
                            </a>
                        </td>
                        <td class="table_left">
                            <a href="#" data-ajax="false">
                                <!--
                                R. Antônio de Andrade, 109 - Canindé<br>
                                São Paulo, SP - CEP 03034-080
                                -->
                                Rua Rio Vermelho, 13 - Canindé<br>
                                São Paulo, SP - CEP 03034-110            </a>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <a href="tel:01133128845" data-ajax="false">
                                <img src="{% static "css/catalogo/img/icomoon-phone.png" %}" alt="Telefone" title="Telefone">
                            </a>
                        </td>
                        <td class="table_left">
                            <a href="tel:01133128845" data-ajax="false">(11) 3312-8845</a>
                            / <a href='tel:01127388935' data-ajax='false'>2738-8935</a>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            &nbsp;
                        </td>
                        <td class="table_left">
                            <a href="{% url "sitewide:index" %}" data-ajax="false">
                                Entrar no Sistema
                            </a>
                        </td>
                    </tr>
                </table>

                
                <script>
                 function openMenu() {
                     $(window).scrollTop(0);
                     $(window).scrollLeft(0);
                     $("#menu").panel("open");
                 }
                </script>

                {% block main %}{% endblock %}

            </div>
        </div>
        
        <script src="{% static "js/catalogo/menuSetup.js" %}"></script>
        <script src="{% static "js/catalogo/dynamicPopup.js" %}"></script>
        
    </body>
</html>

catalogo/templates/catalogo/busca_resultado.html
{% extends 'catalogo/base.html' %}
{% load static %}

{% block title %}Catálogo{% endblock %}

{% block mainTitle %}Catálogo{% endblock %}

{% block main %}
<br>
<div class='categoria_nome'>Resultado da busca '{{ query }}'</div>

{% for item in itens %}

<!-- CARD -->
<div class='card card-3'>
    <a href='#' class='produtos' id='{{ item.produto.codigo }}'>
        <img class="card-img-thumb" src='{% if item.produto.foto %}{{ item.produto.foto.url }}{% else %}{% static "img/question_mark.png" %}{% endif %}' alt='{{ item.produto.codigo }}'>
    </a><br>
    
    {{ item.produto.codigo }}<br>
    {{ item.produto.nome }}<br>
    {{ item.produto.por_caixa }} pçs por caixa
</div>
<!-- END CARD -->

{% endfor %}

{% endblock %}

catalogo/templates/catalogo/index.html
{% extends 'catalogo/base.html' %}

{% block title %}Catálogo{% endblock %}

{% block mainTitle %}Catálogo{% endblock %}

{% block main %}

<button class="index_menu" onclick="openMenu();" data-inline="true">Nossos Produtos</button>

<br><br>
<br><br>
<br><br>
<br><br>
<br><br>

{% endblock %}

catalogo/templates/catalogo/lista.html
{% extends 'catalogo/base.html' %}
{% load static %}

{% block title %}Catálogo{% endblock %}

{% block mainTitle %}Catálogo{% endblock %}

{% block main %}
<br>
<div class='categoria_nome'>{{ lista_nome }}</div>

{% for item in itens %}

<!-- CARD -->
<div class='card card-3'>
    <a href='#' class='produtos' id='{{ item.produto.codigo }}'>
        <img class="card-img-thumb" src='{% if item.produto.foto %}{{ item.produto.foto.url }}{% else %}{% static "img/question_mark.png" %}{% endif %}' alt='{{ item.produto.codigo }}'>
    </a><br>
    
    {{ item.produto.codigo }}<br>
    {{ item.produto.nome }}<br>
    {{ item.produto.por_caixa }} pçs por caixa
</div>
<!-- END CARD -->

{% endfor %}

{% endblock %}

catalogo/templates/catalogo/menu.html
<!-- MENU -->
<div data-role="panel" class="jqm-navmenu-panel" data-position="left" id="menu" data-display="overlay" data-theme="b" data-ajax="false">
    <ul class="jqm-list ui-alt-icon ui-nodisc-icon">

        <li data-icon="home"><a href="{% url "catalogo:index" %}" data-ajax="false">Home</a></li>

        {% for pasta in pastas %}

        {% with pasta_length=pasta.menuitem_set.all|length %}
        
        {% if pasta_length == 1 %}
        <li data-icon='false'>
            <a href="{% url "catalogo:lista" pasta.menuitem_set.first.lista.id %}" data-ajax='false'>
                <span class='no-ellipsis'>{{ pasta.menuitem_set.first.nome }}</span>
            </a>
        </li>

        {% elif pasta_length > 1 %}
        <li data-role='collapsible' data-collapsed-icon='carat-d' data-expanded-icon='carat-u' data-iconpos='right' data-inset='false'>
            <h3><span class='no-ellipsis'>{{ pasta.nome }}</span></h3>
            <ul>
                {% for menu_item in pasta.menuitem_set.all %}
                <li data-icon='false'>
                    <a href="{% url "catalogo:lista" menu_item.lista.id %}" class='submenu-link' data-ajax='false'>
                        <span>{{ menu_item.nome }}</span>
                    </a>
                </li>
                {% endfor %}
            </ul>
        </li>
        {% else %}
        <!-- Pasta {{ pasta.nome }} vazia -->
        {% endif %}
        {% endwith %}

        {% endfor %}
    </ul>
</div>
<!-- END MENU -->